# Generated by Django 3.2.5 on 2021-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210812_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='shipments',
            field=models.ManyToManyField(to='products.Shipment'),
        ),
    ]
